services:
  - type: pserv
    name: livebook
    runtime: elixir
    buildCommand: mix do local.rebar --force, local.hex --force && mix escript.install --force hex livebook 0.13.3
    startCommand: cd /data && /opt/render/project/.mix/escripts/livebook server
    envVars:
    - key: LIVEBOOK_HOME
      value: /data
    - key: LIVEBOOK_PASSWORD
      generateValue: true # Generate a base64-encoded 256-bit value
    - key: LIVEBOOK_PORT
      value: 8080
    - key: ELIXIR_VERSION
      value: 1.17.2
    - key: ERLANG_VERSION
      value: 27.0
    disk: # Persistent disk configuration
      name: data
      mountPath: /data
      sizeGB: 10
