services:
  - type: pserv
    name: livebook
    runtime: docker
    image:
      url: docker.io/my-name/my-image:latest
    envVars:
    - key: LIVEBOOK_HOME
      value: /data
    - key: LIVEBOOK_PASSWORD
      generateValue: true # Generate a base64-encoded 256-bit value
    - key: PORT
      value: 8080
    - key: LIVEBOOK_PORT
      value: 8080
    disk: # Persistent disk configuration
      name: data
      mountPath: /data
      sizeGB: 10
